# RDD2022 India - 9 populated classes
# Place the dataset at: data/RDD2022-India-9class

path: data/RDD2022-India-9class
train: train/images
val: valid/images
test: test/images

names:
  0: D00
  1: D01
  2: D0w0
  3: D10
  4: D11
  5: D20
  6: D40
  7: D43
  8: D44